version: "3"

services:
    "journal_build":
        build:
            dockerfile: Dockerfile
            context: .
        image: pixlmint/journal:2024
        container_name: journal_build
        volumes:
            - data:/var/www/html/data
            - content:/var/www/html/content
            - media:/var/www/html/media
            - backup:/var/www/html/backup
        environment:
            USER_UID: 1000
            USER_GID: 1000
        ports:
            - "94:80"

volumes:
    data:
    media:
    content:
    backup: