version: "3"

services:
  "journal":
    build:
      dockerfile: Dockerfile
      context: .
      args:
        UID: 99
        GID: 100
    image: christiangroeber/journal:2023
    volumes:
      - data:/var/www/html/data
      - content:/var/www/html/content
      - media:/var/www/html/media
      - backup:/var/www/html/backup
    environment:
      SECRET: 'adsf'
    ports:
      - "88:80"

volumes:
  data:
  media:
  content:
  backup: