name: Docker Build

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        uses: actions/setup-node@v3
        name: yarn Install
        with:
          node-version: '14'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile # optional, --immutable
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: christiangroeber/journal:latest
